### ISSUE TITLE
Existing tags are not displayed when adding a new question

### ISSUE THREAD

**Issue by walnutbread24** [Yawan-1/StackOverFlow--Clone#12]
I see that there are tags available in the Tags app but then are not shown to the user on the new question page (and new users are not allowed to create new tags due to low reputation). 
Great project by the way.

**Comment by Yawan-1** [comment]
Hello @nouveauciel, Thanks for your time. But Can you explain in brief, Which tags are not showing in the `new question page` ? and I think That's the real logic I implement "No user will be able to create new tags with low reputation", and this logic is also in real `Stack over flow` site.

**Comment by nouveauciel** [comment]
Hi @Yawan-1 , thanks for looking into this. You are right in your understanding of the issue (I should have made it clearer). The solution could be an autocomplete feature. btw, I found this to be a good solution: [https://github.com/chhantyal/taggit-selectize](url)

Autocompletion almost solves the problem but still has some limitations. Say there are only 10 existing tags available to use, it is hard for new users to discover these available tags with solely autocomplete. e.g. without any hints the user has to try or know the initial keyword to see the list. 

Therefore, I think, in addition to autocompletion, a list of available tags to be shown to allow the user to select or drag and drop. I did a quick research on how this is possible in the UI but did not find a solution off-the-shelf.

**Comment by Yawan-1** [comment]
Thanks @nouveauciel for finding this good package to implement this functionality. But We can also implement this by our own `jquery` function or code and I am pretty sure the package you shared is also using `jquery` [A file which contains js code of all the package](https://github.com/chhantyal/taggit-selectize/blob/faa4cd8d98cecc0562ff265a7cf800cc4a8f4885/taggit_selectize/static/taggit_selectize/js/selectize.js). So the sequence is gonna be like ,

"When the user types in input field then We are gonna attach a _handler_ with _input field_ to send the current value of the field to the backend then Backend will filter all the tags which matches the typed _string_ in the `tag field` then Ajax will show returned tags from **JsonResponse** to the user And Of course `Jquery` is pretty slow But It will be enough for this functionality."

What about this?

**Comment by nouveauciel** [comment]
Hi Yawan, your solution looks great, but I think we are thinking about different things.

I am proposing to add a list of available tags before the user types anything. for example, the user can click and choose among existing tags without typing any letters. 

This is actually a different functionality from StakOverflow, which is more suitable for a smaller site where there aren't many tags to choose from. Just an idea for your consideration. :D

**Comment by Yawan-1** [comment]
Hello @nouveauciel, Yes your idea is also good about "Showing tags without any user input in input field", but there are some downsides of this feature like,

1. If user is asking a question about `React Js` and we've shown tags like `python`, `ruby`, `bootstrap`, `aws`, then user will kinda frustrate looking at the tags.

> **Solution**: This can be possible if we can identity the `programming language` or `specific keyword/strings` used in *question body field* and suggest tags based on identified data. 

but It is also good thinking about this feature. It's really helpful. and I think `so` already have this functionality.
