### ISSUE TITLE
Problem with static files

### ISSUE THREAD

**Issue by alexandervidyaev** [Yawan-1/StackOverFlow--Clone#13]
Hello. I have problem with static files like this:
![image](https://user-images.githubusercontent.com/72314711/195358308-acb27e63-88a8-446b-86bf-d7e4642fd11f.png)  
![image](https://user-images.githubusercontent.com/72314711/195358375-845598d0-eff8-4ab8-9b77-d4bdae88189b.png)  
and other stuff. But admin console works perfectly with css:  
![image](https://user-images.githubusercontent.com/72314711/195358573-27e4e64f-d530-4ae1-8236-ecf4c77c3e08.png)  

Idk why, but nginx works right with admin console, there is it logs:  
![image](https://user-images.githubusercontent.com/72314711/195359240-7de6372e-89c3-4c0e-9bfa-2f6cdf8f6e49.png)

Site logs: 

![image](https://user-images.githubusercontent.com/72314711/195360072-1a28e46d-b862-4446-ae39-5ce16fc9925a.png)

Nginx config:
<pre><code>
upstream main {
    server web:8000;
}

server {

    listen 80;
    location / {
        proxy_pass http://main;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        client_max_body_size 100M;
    } 
    location /static/ {
        alias /home/app/web/staticfiles/;
    }
}
</pre></code>
Docker-compose
<pre><code>
version: '3.8'

services:
  web:
    build: .
    #command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    command: /bin/sh -c "gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./staticfiles/:/usr/src/app/staticfiles/
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.0
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./staticfiles/:/home/app/web/staticfiles/
    depends_on:
      - web
</pre></code>

**Comment by Yawan-1** [comment]
Hello @alexandervidyaev , I have seen the logs and there is nothing wrong in your `Nginx configuration`. The problem is in the `CSS`'s serving URL which I used of stack over flow's production CSS and They changed their production CSS so my App's CSS is  broke with it, [Take a look at it](https://github.com/Yawan-1/StackOverFlow--Clone/issues/11#issuecomment-1264542140). But I have plans to fix this in few days.
