### ISSUE TITLE
Profile_photo dont update

### ISSUE THREAD

**Issue by svanberg90** [Yawan-1/StackOverFlow--Clone#14]
Hi
When you choose a new profile picture, no new path to the picture is written to the database.

**Comment by Yawan-1** [comment]
Hello @svanberg90 , Thanks for pointing out, I will look it as soon as possible.

**Comment by Yawan-1** [comment]
@svanberg90 , I have fixed the issue. Now You can edit the profile image and It will save without any problem.

**Comment by svanberg90** [comment]
very good job. I have tried different solutions. Found a fix, but it wasn't optimal. Going to do a pull.
