### ISSUE TITLE
Please provide static UI

### ISSUE THREAD

**Issue by vivekabcbank** [Yawan-1/StackOverFlow--Clone#16]
Can you please provide static UI

**Comment by Yawan-1** [comment]
Hey there @vivekabcbank, What do you mean? I mean like what kind of static UI do you want me to add? Like, some site map, or link disappearing which are not functional

**Comment by vivekabcbank** [comment]
I mean can you provide static template of this project.

**Comment by Yawan-1** [comment]
@vivekabcbank , I still don't get it, explain with some example.

**Comment by vivekabcbank** [comment]
HTML, CSS static template I mean template.

**Comment by Yawan-1** [comment]
Hello @vivekabcbank, There are templates and static files with the project. you can check project's [templates here](https://github.com/Yawan-1/StackOverFlow--Clone/tree/master/templates) and static [files here](https://github.com/Yawan-1/StackOverFlow--Clone/tree/master/static)
