### ISSUE TITLE
A server error occurred.  Please contact the administrator.

### ISSUE THREAD

**Issue by josephjw** [Yawan-1/StackOverFlow--Clone#18]
please give me steps to solve this 

And i m not using PostgreSQL i just commented i m using sqlite even thought i m getting same

**Comment by Yawan-1** [comment]
Can you tell me what is the error? Can you post it here?

**Comment by controldevil007** [comment]
the error solved itself once i installed wheel pakage and removed the version number from typed-ast in requirements.txt

**Comment by controldevil007** [comment]
> please give me steps to solve this
> 
> And i m not using PostgreSQL i just commented i m using sqlite even thought i m getting same

the error solved itself once i installed wheel and removed the version number from typed-ast in requirements.txt
