### ISSUE TITLE
No way for a user to up/down vote on questions and answers

### ISSUE THREAD

**Issue by JeffreyZZ** [Yawan-1/StackOverFlow--Clone#21]
It seems that there is no way for a user to up/down vote on questions and answers as the rewardPrivielege() cannot be called in any path to update user's comment_everywhere_Priv, voteDownPriv and voteUpPriv for a new user，even though that the user may have enough reputation.

**Comment by Yawan-1** [comment]
Hi, I totally forget about this issue. I think I implemented a function to upvote/downvote on questions and answers, no?
