### ISSUE TITLE
When I try to pip install -r requirements.txt command in local server there shows some errors

### ISSUE THREAD

**Issue by razuahmedjoy** [Yawan-1/StackOverFlow--Clone#3]
![Screenshot 2022-01-31 145718](https://user-images.githubusercontent.com/58605204/151765060-5d3862fe-e333-4e5d-a380-9cc110e61189.png)

**Comment by Yawan-1** [comment]
Hey razuahmedjoy, Can you tell me the version of **Pip** you are using ?
