### ISSUE TITLE
it does not update the users

### ISSUE THREAD

**Issue by rodrigo1525** [Yawan-1/StackOverFlow--Clone#6]
I'm testing it locally and with sqlite and it doesn't let me update the users and it doesn't let me mark the correct answer and vote for the answers

**Comment by Yawan-1** [comment]
What does it show ? Any errors in terminal ?

**Comment by Yawan-1** [comment]
@rodrigo1525 Hello Rodrigo, Thanks for pointing that out, I have replaced `HTTP is_ajax method` with my own `is_ajax function`. Now it should not show the error.

**Comment by Yawan-1** [comment]
@rodrigo1525, Hello there, I think you misunderstood it, of course the first one will not be able to vote it, it takes about 15 reputation to vote up.

> **he will not be able to select the correct answer as well**

I checked the [functiion](https://github.com/Yawan-1/StackOverFlow--Clone/blob/master/qa/views.py#L3203) and user can mark as accept answer without any restrictions.
