### ISSUE TITLE
does not vote

### ISSUE THREAD

**Issue by mavlarado98** [Yawan-1/StackOverFlow--Clone#8]
does not allow up or down votes.

At first it wouldn't let me select the correct answer due to a design error that forces you to vote for the answer you are selecting as correct.

I altered the code a bit to allow me to select the correct answer and raise reputation and get to select 2 correct answers raising to 30 reputation without voting for the correct answer.

At the time of voting it keeps throwing me the error having the user 30 of reputation.

![Captura de pantalla (13)](https://user-images.githubusercontent.com/103960293/163873042-eec6fc9f-6182-430b-8351-688e5e85f991.png)

error that appears in the local server

`Cannot Make another Edit
Printing the Last Edit Vote Status

[18/Apr/2022 14:22:25] "GET /questionDetailView/1/ HTTP/1.1" 200 188151
[18/Apr/2022 14:22:26] "POST /martor/markdownify/ HTTP/1.1" 200 0
[18/Apr/2022 14:22:30] "GET /answer_upvote_downvote/1/?submit=like HTTP/1.1" 200 29`

**Comment by Yawan-1** [comment]
Are you logged in ? Did you earned that privilege to Vote ? If not then, turn upvote privilege Boolean to `True` in Django Admin. and Inform me

**Comment by mavlarado98** [comment]
Thank you.
good project

**Comment by Yawan-1** [comment]
@mavlarado98 , Your Welcome
